services:
  php:
    container_name: pos
    image: pos_php
    build: build/php
    volumes:
      - ../:/var/www/html
    ports:
      - 80:80
    environment:
      - NETTE_DEBUG=1
    links:
      - db
  db:
    container_name: pos_db
    image: pos_db
    build: build/database
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=pos
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=pos
    volumes:
      - pos-datavolume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_pos
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=pos
      - PMA_PASSWORD=test
volumes:
  pos-datavolume: